Landing Page
djaro-mest-capston-2/djaro-trips-web pull request #69
Opened 2024-04-12 11:14 UTC by BlessOnyi

Worked on the Landing Page

2024-04-12 22:00 UTC, ushashir requested changes
Pulll from develop, resolve conflicts and push again

2024-04-12 22:00 UTC, ushashir commented on public/index.html
> +    <link href="styles.css" rel="stylesheet">
remove this`<link href="styles.css" rel="stylesheet">`

2024-04-13 08:09 UTC, BlessOnyi commented
I have merged the conflict and pushed

2024-04-13 11:50 UTC, ushashir approved these changes

2024-04-13 11:51 UTC, merged